//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversitySQL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Destytojas
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Destytojas()
        {
            this.Dalykas = new HashSet<Dalykas>();
        }
    
        public string Asmens_Kodas { get; set; }
        public string Fakultetas { get; set; }
        public string Vardas { get; set; }
        public string Pavarde { get; set; }
        public string Laipsnis { get; set; }
    
        public virtual Fakultetas Fakultetas1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dalykas> Dalykas { get; set; }
    }
}
